---
- datetime:
    text_size: md
    locale: en-GB
    format:
      dateStyle: short
      timeStyle: short
      hour12: false
- greeting:
    text_size: md
    text: "{{HOMEPAGE_VAR_BASE_DOMAIN}} homepage"
- openmeteo:
#    label: Kyiv # optional
    latitude: 7.880448
    longitude: 98.392251
#    timezone: Europe/Kiev # optional
    units: metric # or imperial
    cache: 5 # Time in minutes to cache API responses, to stay within limits
    format: # optional, Intl.NumberFormat options
      maximumFractionDigits: 1
- resources:
    cpu: true
    memory: true
    disk: /
    uptime: true
    refresh: 3000 # optional, in ms
    diskUnits: bytes # optional, bytes (default) or bbytes. Only applies to disk
